### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by vinayaksable2399** [EdmundMartin/image_classifier#1]
c.train_model('my_example_model')
---------------------------------
Run id: COQYT4
Log directory: log/
Traceback (most recent call last):

  File "<ipython-input-100-1c73f92de04b>", line 1, in <module>
    c.train_model('my_example_model')

  File "<ipython-input-89-08947be32086>", line 206, in train_model
    batch_size=batch_size)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\models\dnn.py", line 216, in fit
    callbacks=callbacks)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 288, in fit
    self.summ_writer, self.coord)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py", line 748, in initialize_fit
    self.n_train_samples = len(get_dict_first_element(feed_dict))

TypeError: object of type 'NoneType' has no len()

**Comment by EdmundMartin** [comment]
I am closing this as there is not enough information for me to tell what went wrong. 

Looks like you tried to train a model without providing training data-sets which is why you got the NoneType has no length error. Or potentially you are using a different version of the underlying libraries, as it appears you are using your Anacondas site packages instead of a virtual environment.
